# Generated by Django 5.1.7 on 2025-03-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('groups', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('published_year', models.PositiveBigIntegerField()),
            ],
        ),
    ]
